server {
    listen 443 ssl;
    server_name loki.healio.tech;

    ssl_certificate /etc/nginx/certs/ca/server.crt;
    ssl_certificate_key /etc/nginx/certs/ca/server.key;

    # Temporary: keep this OFF until client certs are wired
    ssl_verify_client off;

    location /loki/ {
        proxy_pass http://loki:3100/;
    }
}

server {
    listen 443 ssl;
    server_name falco.healio.tech;

    ssl_certificate /etc/nginx/certs/ca/server.crt;
    ssl_certificate_key /etc/nginx/certs/ca/server.key;

    # Temporary: keep this OFF until client certs are wired
    ssl_verify_client off;

    location / {
        proxy_pass http://falcosidekick:2801;
    }
}
